# Generated by Django 3.2.5 on 2021-07-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager', '0002_auto_20210731_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='coefficient',
            field=models.IntegerField(null=True),
        ),
    ]
